title : oemof Workshop on Modeling of Heat Pumps
author: Francesco Witte and Patrik Schönfeld
logo: figures/logo_oemof_mid.svg
email: francesco.witte@dlr.de

# Short description about the book
description: >-
  Workshop combining thermodynamic simulation of heat pumps and their application in energy system optimization

execute:
  execute_notebooks           : cache
  timeout                     : 100

# HTML-specific settings
html:
  home_page_in_navbar         : false
  use_issues_button: true
  use_repository_button: true
  favicon: "logo_oemof_small.svg"

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/fwitte/oemof-workshop-osmses-2023
  path_to_book                : "workshop"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

# math settings
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
